### PR TITLE
Show interactive Plotly image (html-js-based) on the `Step 2` page

### PR DESCRIPTION
**Pull request by AndrewSazonov**
An example of simple html-js-based implementation of using Plotly.js is added

### CODE REVIEW

**Comment by AndrewSazonov** [comment]
Currently based on `develop` branch of `easyApp`

**Comment by ConradPomm** [comment]
Plotly demo recently worked for me, but with the current updates I get the following error:
file:///C:/_EasyScience/easyTextureApp/EasyTextureApp/Gui/Pages/Step2/SideBarGroups/SubStep3.qml:46: 
TypeError: Cannot call method 'generateYArrayValues' of undefined

**Comment by AndrewSazonov** [comment]
Have you switch to `develop` branch for `easyApp`?

**Comment by ConradPomm** [comment]
Actually, I did not. But now, after I have done so, I still have the same problem.

**Comment by ConradPomm** [comment]
Problem was on my side. Works fine with easyApp on develop branch.

**Pull request merged**
